[tox]
requires =
    tox>=3.28.0
envlist = 3.10
skipsdist = true

[testenv]
passenv = VRSCRPCURL
          VARRRRPCURL
          VDEXRPCURL
          INFURAURL
          ETHERSCANAPIKEY
          APIPORT


deps =
    -rrequirements.txt
    -rrequirements.dev
    pytest
    pytest-timeout
    pytest-xdist

#--profile
#pytest-profiling

commands =
    # python3 generate_missing_tests.py
    pytest -vv --color=yes --log-cli-level=DEBUG --disable-warnings --timeout=60 -n auto
    pytest --durations 10

